Fix error in the test related to Ldap container - java.lang.IllegalSt…
linagora/tmail-backend pull request #735
Opened 2023-06-16 04:37 UTC by vttranlina

…ateException: Mapped port can only be obtained after the container is started

- Reason: Tmail-backend server extension tries to get LdapHost before Ldap already start

2023-06-17 05:39 UTC, chibenwa approved these changes

2023-06-19 03:04 UTC, Arsnael requested changes
This PR requires a rebase and need to have back the James upgrade commits that have been reverted lately, as this PR is supposed to fix issues based on those.

2023-06-19 06:03 UTC, Arsnael approved these changes

2023-06-20 03:57 UTC, quantranhong1999 approved these changes

2023-06-20 03:57 UTC, merged